title: Beauty Bust
email: your-email@example.com
# description: >- # this means to ignore newlines until "baseurl:"
#   Write an awesome description for your new site here. You can edit this
#   line in _config.yml. It will appear in your document head meta (for
#   Google search results) and in your feed.xml site description.
#baseurl: "/BeautyBust" # the subpath of your site, e.g. /blog
url: "https://thebeautybust.co.uk" # the base hostname & protocol for your site, e.g. http://example.com
image-path: /assets/img/

insta_username: thebeautybust
linkedin_username: virginia-turner-301220246

# Build settings
theme: minima
plugins:
  - jekyll-feed